export interface toCFDI {
  id:                 number,
  version:            string,
  serie:              string,
  folio:              string,
  fecha:              Date,
  fecha_impt:         Date,
  t_comprobante:      string,
  forma_pago:         string,
  moneda:             string,
  sub_total:          number,
  descuento:          string | null,
  total:              number,
  tipo_cambio:        string,
  metodo_pago:        string,
  no_certificado:     string,
  lugar_expedicion:   string,
  emisor_rfc:         string,
  emisor_nombre:      string,
  emisor_regimen_f:   string,
  emisor_regimen_f2:  null,
  emisor_domicilio:   null,
  emisor_expedido:    null,
  receptor_rfc:       string,
  receptor_nombre:    string,
  receptor_domicilio: string,
  receptor_regimen:   string,
  receptor_uso_cfdi:  string,
  comp_timbre_version: string,
  comp_fecha_timbrado: Date,
  comp_sello_cfd:      string,
  comp_certificado:    string,
  comp_rfc_proov:      string,
  conceptos:           ConceptoById[]
}


export interface ConceptoById {
  claveProdServ:     string,
  noIdentificacion:  string,
  cantidad:          number,
  claveUnidad:       string,
  unidad:            string,
  descripcion:       string,
  valorUnitario:     number,
  importe:           number,
  descuento:         string | null,
  objetoImp:         string,
}
